# Copyright (c) 2024 FORCERA, LDA
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
# 
# SPDX-License-Identifier: EPL-2.0

services:
  mqtt:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "9001:9001"
      - "1883:1883"
    environment:
        - LOCAL_MQTT_BROKER=${LOCAL_MQTT_BROKER:-mosquitto}
        - MQTT_PORT=${MQTT_PORT:-1883}
        - DRONE_MQTT_TOPIC=${DRONE_MQTT_TOPIC:-drone/telemetry_data}
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server
    container_name: spade_redis_1
